//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueueReceiver.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QueueReceiver.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not relevant, removing message from queue.
        /// </summary>
        internal static string GroupDoesNotExist {
            get {
                return ResourceManager.GetString("GroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message handler encountered an exception.
        /// </summary>
        internal static string MessageHandlerException {
            get {
                return ResourceManager.GetString("MessageHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message completed successfully.
        /// </summary>
        internal static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person doesn&apos;t exist in db so there is no reson to remove access, removing message from queue.
        /// </summary>
        internal static string PersonDoesNotExist {
            get {
                return ResourceManager.GetString("PersonDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person with  oid {0} could not be found in the database.
        /// </summary>
        internal static string PersonWasNotFoundOrCreated {
            get {
                return ResourceManager.GetString("PersonWasNotFoundOrCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing access for person with id: {0}, to plant {1}.
        /// </summary>
        internal static string RemoveAccess {
            get {
                return ResourceManager.GetString("RemoveAccess", resourceCulture);
            }
        }
    }
}
